### ISSUE TITLE
doxygen isn't installed

### ISSUE THREAD

**Issue by stevenjswanson** [NVSL/gtron_devel#16]

**Comment by stevenjswanson** [comment]
Shouldn’t there be a commit to come with it?

If you say “resolves  #16” in your commit message, it’ll automatically clear the issue when you push the change.

-steve

**Comment by MichaelMGonzalez** [comment]
I didn't know that - I'll keep that trick in mind for the future
This was the commit: f44c793e3eb226bd988048afc1dff56532654030
