### ISSUE TITLE
gtron update fails if branch isn't master or develop

### ISSUE THREAD

**Issue by MichaelMGonzalez** [NVSL/gtron_devel#7]
This may be its intended behavior; but, I thought I should point it out if we ever want more than one person working on a branch other than develop.

I created my own branch on JetComponents so my changes wouldn't interfere with anybody else who may be working on it. I ran 'gtron update' while still on this branch and received a [FAILED] for JetComponents.  Even though the branch had already been pushed, git doesn't automatically know how to handle the branch with just a plain 'git pull' The log file contained the following error:

There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

```
git pull <remote> <branch>
```

If you wish to set tracking information for this branch you can do so with:

```
git branch --set-upstream-to=origin/<branch> BOM
```

Command 'git pull' returned non-zero exit status 1

**Comment by stevenjswanson** [comment]
It sounds like the problem is that gtron update fails if the branch doesn't exist upstream.   If you do `git branch --set-upstream-to=origin/<branch> BOM` as it suggests, does update work then?

**Comment by MichaelMGonzalez** [comment]
I got this error from just copying and pasting 'git branch --set-upstream-to=origin/<branch> BOM':
bash: branch: No such file or directory

'git push -u' fixed the issue though

**Comment by stevenjswanson** [comment]
But it remains a problem:

Gtron shouldn't fail when trying to update a directory for which there is a local branch.  it should just detect that the branch is new and not pull.

**Comment by stevenjswanson** [comment]
Fixed.
